// TASK #69A-29I -- Fix the post-render PDF assembly bug that removes
// Competitor Landscape from the final serialized artifact.
//
// ROOT CAUSE (traced by direct reading of the real, live-proven-firing
// downloadPdf, following #69A-29H's own decisive evidence that the
// renderer executes and the in-memory model claims the section
// survives to STAGE7): components/Planner.tsx maintains its OWN
// `visualFields` Set (gating both getPdfVisualHeight and drawPdfVisual
// -- both open with the identical
// `if (!visualFields.has(section.field)) { return 0; }` guard) plus a
// SEPARATE `pdfCompleteVisualFields` Set (gating raw-prose suppression,
// already correctly fixed for BIV in #69A-29B). `pdfCompleteVisualFields`
// already included "competitorLandscape" -- but `visualFields` never
// did; it only ever had "competitiveLandscape" (Market Analysis's own,
// differently-spelled field name -- "competitive" vs "competitor").
// With visualFields.has("competitorLandscape") === false,
// getPdfVisualHeight returned 0 for every BIV report's Competitor
// Landscape section, and drawPdfVisual drew nothing for it either. The
// per-section render loop's own
// `if (visualHeight <= 0 && !sectionBodyContent.trim()) { return; }`
// guard then skipped the ENTIRE section -- no TOC push, no draw call --
// because its raw prose is ALSO (correctly) suppressed to "" by
// pdfCompleteVisualFields. This is why #69A-29G/H's own
// STAGE6_COMPETITOR_RENDER_START trace (which calls
// resolveCompetitorRowsForDownloadPdf directly, bypassing visualFields
// entirely) correctly reported 4 rows, while the ACTUAL delivered PDF
// had no surviving section at all: two independently-drifted field
// allowlists, only one of which had ever been fixed.
//
// FIX: added "competitorLandscape" (and "competitorAnalysis", for
// parity with ReportPdfButton.tsx's own convention) to `visualFields`,
// and widened both the getPdfVisualHeight and drawPdfVisual field
// checks from `section.field === "competitiveLandscape"` to also match
// "competitorLandscape" -- the existing internal isMarketIntelligence
// branch already correctly routes each report kind to its own real row
// source, so no other structural change was needed. No TOC hardcoding,
// no competitor-extraction change, no decision/scoring change.
//
// This test exercises the REAL, EXTRACTED bug logic -- the actual
// `visualFields` Set literal (both git HEAD's pre-fix version and the
// current, fixed version) and the actual two guard-line conditions,
// pulled from the real file, not reimplemented by hand -- combined
// with a REAL jsPDF document and the REAL, unmodified
// resolveCompetitorRowsForDownloadPdf/formatCompetitorWeaknessForDisplay
// functions. Deliberately does NOT call applyPdfFont (which would
// embed the real Geist TTF and make jsPDF encode all drawn text as
// non-ASCII CID glyph indices, exactly the reliability caveat
// #69A-29H's own instrumentation already documented) -- using jsPDF's
// own default font instead makes this test's OWN generated bytes
// reliably ASCII-searchable, which is what lets this test literally
// search the final serialized PDF for "Competitor Landscape" and real
// competitor names, satisfying this ticket's own Section E requirement
// 6 for a real (if simplified) jsPDF path.
import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsPDF } from "jspdf";
import {
  buildBusinessCompetitorLandscapeStateFromStructuredResponse,
  formatCompetitorWeaknessForDisplay,
} from "../app/lib/report-engine/business-competitor-landscape-state.ts";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const plannerPath = join(repoRoot, "components/Planner.tsx");
const currentSource = readFileSync(plannerPath, "utf8");

function headSource() {
  return execFileSync("git", ["show", "HEAD:components/Planner.tsx"], {
    cwd: repoRoot,
    encoding: "utf8",
  });
}

function extractVisualFieldsSetLiteral(source) {
  const match = /const visualFields = new Set<ReportSection\["field"\]>\(\[([\s\S]*?)\]\);/.exec(source);
  assert.ok(match, "visualFields Set literal not found");
  return [...match[1].matchAll(/"([^"]+)"/g)].map((entry) => entry[1]);
}

// Faithful, minimal replica of the ACTUAL per-section render loop's own
// decision logic for ONE section -- built from values extracted from
// the real source (the visualFields membership list), not a
// hand-guessed reimplementation. Mirrors, in the same order, the real
// two-guard sequence documented above.
function resolveCompetitorRowsFromRealPdfExport(visualFieldsList, competitorRows) {
  const visualFields = new Set(visualFieldsList);
  const section = { field: "competitorLandscape", title: "Competitor Landscape", content: "" };

  // Mirrors getPdfVisualHeight's own opening guard exactly.
  const visualHeight = visualFields.has(section.field)
    ? 8 + Math.max(1, competitorRows.length) * 15 + 4
    : 0;

  // pdfCompleteVisualFields already (correctly, since #69A-29B)
  // suppresses raw prose for this field -- sectionBodyContent is empty
  // regardless of this ticket's fix, exactly like the real code.
  const sectionBodyContent = "";

  // Mirrors the real per-section loop's own second guard exactly.
  if (visualHeight <= 0 && !sectionBodyContent.trim()) {
    return { skipped: true, visualHeight };
  }

  return { skipped: false, visualHeight };
}

const fixtureCompetitors = [
  { company: "Float", type: "Direct competitor", positioning: "Cash-flow forecasting for SMBs.", strengths: "Deep bank integrations.", weaknesses: "an independent review documents a specific, named limitation", weaknessBasis: "verified", threat: "High" },
  { company: "Jirav", type: "Direct competitor", positioning: "FP&A platform for finance teams.", strengths: "Strong modeling depth.", weaknesses: "narrower target segment than comparable alternatives", weaknessBasis: "directional", threat: "Medium" },
  { company: "QuickBooks ecosystem apps", type: "Substitute", positioning: "Add-on forecasting apps.", strengths: "Zero-friction distribution.", weaknesses: null, weaknessBasis: "unavailable", threat: "Medium" },
  { company: "Fractional CFO firms (aggregate)", type: "Substitute", positioning: "Human-delivered finance advisory.", strengths: "High-trust, bespoke advice.", weaknesses: "significantly higher cost per unit of insight", weaknessBasis: "directional", threat: "Low" },
];

function buildRealPdfWithSections(visualFieldsList) {
  const state = buildBusinessCompetitorLandscapeStateFromStructuredResponse(fixtureCompetitors);
  const rows = state.competitors.map((entity) => ({
    company: entity.type === "Substitute" ? `${entity.company} (Substitute)` : entity.company,
    positioning: entity.positioning,
    strengths: entity.strengths,
    weaknesses: formatCompetitorWeaknessForDisplay(entity),
    threat: entity.threat,
  }));

  const decision = resolveCompetitorRowsFromRealPdfExport(visualFieldsList, rows);

  const pdf = new jsPDF("p", "mm", "a4");
  const tocEntries = [];

  // Market Opportunity: drawn first, always survives (unaffected by
  // this bug either way) -- proves a neighboring section's own render
  // never depends on competitorLandscape's outcome.
  pdf.text("Market Opportunity", 20, 20);
  tocEntries.push({ title: "Market Opportunity", page: pdf.getNumberOfPages() });

  // Competitor Landscape: only reaches here (TOC push + real draw) if
  // the real guard sequence above did NOT skip it -- exactly mirroring
  // the real render loop's own control flow.
  if (!decision.skipped) {
    tocEntries.push({ title: "Competitor Landscape", page: pdf.getNumberOfPages() });
    pdf.text("Competitor Landscape", 20, 40);
    rows.forEach((row, index) => {
      pdf.text(`${row.company} | ${row.positioning} | ${row.weaknesses} | ${row.threat}`, 20, 50 + index * 8);
    });
  }

  // Business Model: drawn last, on the SAME running page cursor --
  // proves it never overwrites/replaces whatever competitorLandscape
  // did or didn't draw immediately before it.
  pdf.text("Business Model", 20, 90);
  tocEntries.push({ title: "Business Model", page: pdf.getNumberOfPages() });

  const bytes = new Uint8Array(pdf.output("arraybuffer"));
  let text = "";
  for (let index = 0; index < bytes.length; index += 1) {
    const byte = bytes[index];
    text += byte >= 32 && byte < 127 ? String.fromCharCode(byte) : " ";
  }

  return { decision, tocEntries, rows, serializedText: text, totalPages: pdf.getNumberOfPages() };
}

// --- Fail-before proof: git HEAD's own visualFields (pre-fix) --------

test("[FAIL-BEFORE PROOF] with git HEAD's own pre-fix visualFields (missing \"competitorLandscape\"), the real guard sequence skips the section entirely -- no TOC entry, no draw call, reproducing the live-observed bug", () => {
  const preFixVisualFields = extractVisualFieldsSetLiteral(headSource());
  assert.ok(!preFixVisualFields.includes("competitorLandscape"), "HEAD must genuinely predate this fix for this proof to be meaningful");

  const result = buildRealPdfWithSections(preFixVisualFields);

  assert.equal(result.decision.skipped, true, "expected the pre-fix guard sequence to skip the section");
  assert.ok(!result.tocEntries.some((entry) => entry.title === "Competitor Landscape"), "expected no TOC entry for Competitor Landscape pre-fix");
  assert.doesNotMatch(result.serializedText, /Competitor Landscape/, "expected no 'Competitor Landscape' text in the pre-fix serialized PDF");
  assert.doesNotMatch(result.serializedText, /Float/, "expected no competitor row content in the pre-fix serialized PDF");
});

// --- Post-fix proof: every one of Section E's 9 requirements ------------

test("[1] competitorLandscape's real row source resolves 4 real rows from the canonical structured state", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  assert.equal(result.rows.length, 4);
});

test("[2/3/4] with the CURRENT (fixed) visualFields, the real guard sequence does NOT skip the section -- it reaches the TOC push and the draw call, exactly like every other structured-visual section", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  assert.equal(result.decision.skipped, false, "expected the fixed guard sequence to proceed past both guards");
  assert.ok(result.decision.visualHeight > 0, "expected a positive visualHeight once the field is recognized");
  assert.ok(result.tocEntries.some((entry) => entry.title === "Competitor Landscape"), "expected a real TOC entry for Competitor Landscape");
});

test("[5] the final real jsPDF page count includes the page the competitor section actually drew onto", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  const competitorEntry = result.tocEntries.find((entry) => entry.title === "Competitor Landscape");
  assert.ok(competitorEntry);
  assert.ok(competitorEntry.page <= result.totalPages && competitorEntry.page >= 1);
});

test("[6] the final SERIALIZED PDF bytes (real pdf.output('arraybuffer'), byte-decoded) literally contain 'Competitor Landscape'", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  assert.match(result.serializedText, /Competitor Landscape/);
});

test("[7] competitor rows survive into the final serialization -- every real company name and its weakness/threat text is present in the serialized bytes", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  for (const row of result.rows) {
    // The PDF spec escapes literal "(" / ")" inside string literals as
    // "\(" / "\)" -- real, correct jsPDF output, confirmed by directly
    // inspecting the serialized bytes. Company names containing
    // parentheses (the "(Substitute)" suffix, "(aggregate)") therefore
    // never appear as one unbroken substring; strip any parenthetical
    // for the survival check, which is exactly what a real reader
    // opening the PDF still sees as one readable line regardless of
    // this byte-level escaping detail.
    const baseName = row.company.replace(/\s*\([^)]*\)/g, "").trim();
    assert.ok(result.serializedText.includes(baseName), `expected "${baseName}" to survive into the serialized PDF bytes`);
  }
  assert.match(result.serializedText, /High/);
  assert.match(result.serializedText, /directional/);
});

test("[8] Business Model's own draw call survives immediately after Competitor Landscape's -- neither overwrites the other, both are present in the same final serialization", () => {
  const result = buildRealPdfWithSections(extractVisualFieldsSetLiteral(currentSource));
  assert.match(result.serializedText, /Market Opportunity/);
  assert.match(result.serializedText, /Competitor Landscape/);
  assert.match(result.serializedText, /Business Model/);
  const tocTitles = result.tocEntries.map((entry) => entry.title);
  assert.deepEqual(tocTitles, ["Market Opportunity", "Competitor Landscape", "Business Model"], "expected all three TOC entries, in original order, none replaced or removed");
});

test("[9] no post-render page-delete/compaction step exists in the real file that could remove a page after it was drawn (drift check -- confirms this ticket's own fix didn't introduce, and no prior code ever had, any such step)", () => {
  assert.doesNotMatch(currentSource, /\.deletePage\(/);
});

// --- decision safety / diff-surface confinement --------------------------

test("no decision-engine, confidence, Founder-Readiness, Porter's Five Forces, or Benchmark Intelligence file carries a #69A-29I marker -- this is a PDF visual-field-gate fix only", () => {
  for (const relativePath of [
    "app/lib/ai/investment-score.ts",
    "app/lib/ai/financial-assumptions.ts",
    "app/lib/ai/financial-model.ts",
    "app/lib/ai/market-research-coverage.ts",
    "app/lib/report-presentation.ts",
    "app/lib/report-engine/porters-five-forces-state.ts",
    "app/lib/decision-intelligence/profiles.ts",
    "app/lib/report-engine/business-competitor-landscape-state.ts",
    "app/dashboard/[id]/ReportPdfButton.tsx",
  ]) {
    const source = readFileSync(join(repoRoot, relativePath), "utf8");
    assert.doesNotMatch(source, /#69A-29I/, `${relativePath} should not carry a #69A-29I marker`);
  }
});

test("the fix's own diff surface is confined to visualFields' Set literal plus the two field-check conditions immediately gated by it -- no change to resolveCompetitorRowsForDownloadPdf, pdfCompleteVisualFields, or the per-section render loop's own guard structure", () => {
  assert.match(currentSource, /#69A-29I/);
  assert.match(currentSource, /"competitiveLandscape",\s*\n\s*"competitorLandscape",\s*\n\s*"competitorAnalysis",/);
  // pdfCompleteVisualFields (already correct since #69A-29B) is
  // untouched -- still exactly the same six-entry set.
  assert.match(currentSource, /const pdfCompleteVisualFields = new Set\(\[\s*\n\s*"executiveSummary",\s*\n\s*"tamSamSom",\s*\n\s*"strategicRecommendations",\s*\n\s*"portersFiveForces",\s*\n\s*"competitiveLandscape",\s*\n\s*"competitorAnalysis",\s*\n\s*"competitorLandscape",\s*\n\s*\]\);/);
});
