import UIKit
import Capacitor

/**
 * Registers this app's own Capacitor plugins.
 *
 * WHY THIS EXISTS: Capacitor does not discover plugins by scanning the
 * Objective-C runtime. CapacitorBridge.registerPlugins() builds its list from
 * the `packageClassList` array inside the bundled capacitor.config.json, and
 * that array is generated by `cap sync` from installed npm plugin PACKAGES.
 * A plugin that lives in the app target -- as AppAttestPlugin does -- can
 * never appear there, so it is compiled into the binary and simply never
 * reached. That is exactly the failure this fixes: the class existed, and
 * JavaScript had no way to see it.
 *
 * Editing capacitor.config.json by hand would appear to work and is the wrong
 * answer: that file is in ios/.gitignore and is regenerated by every
 * `cap sync`, so the registration would silently disappear.
 *
 * WHY HERE: capacitorDidLoad() runs immediately after the bridge is created
 * and before loadWebView(), so the plugin's JSExport user script is installed
 * at .atDocumentStart before the page is fetched. The JavaScript side calls
 * registerPlugin("AppAttest"), which resolves its native implementation from
 * Capacitor.PluginHeaders once, at that moment -- so registering any later
 * than this would leave the web layer permanently believing the plugin is
 * absent.
 *
 * registerPluginInstance is used rather than registerPluginType because the
 * latter returns early whenever autoRegisterPlugins is true, which is the
 * default and which the SplashScreen plugin relies on.
 */
class MainViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()

        // CAPBridgeProtocol does not expose plugin registration, so this needs
        // the concrete bridge. `CapacitorBridge` is an open class and
        // registerPluginInstance is public, so this is supported API, not a
        // reach into Capacitor's internals.
        guard let bridge = bridge as? CapacitorBridge else {
            return
        }

        bridge.registerPluginInstance(AppAttestPlugin())
    }
}
